databases:
  - name: napoli-db
    databaseName: napoli
    user: napoli
    plan: free

services:
  - type: web
    name: 60-seconds-to-napoli
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn restaurant_api.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: napoli-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.4"
